export const dataPhotos =[
    {
        id: 1,
        name: "Bonifacio",
        date: "12/12/2023",
        description: "Explora las fotos de Bonifacio y revive los buenos momentos.",
        image:  "/assets/bonifacio.jpg",
        url: "https://drive.google.com/drive/folders/16r4_mC-nAEOEUGEe22O76l7JD9hisX8q",
    },
    {
        id: 2,
        name: "Casbas",
        date: "10/1/2024",
        description: "Explora las fotos de Bonifacio y revive los buenos momentos.",
        image:  "/assets/bonifacio-OpenAir.jpg",
        url: "https://drive.google.com/drive/folders/16r4_mC-nAEOEUGEe22O76l7JD9hisX8q",
    },
    {
        id: 3,
        name: "Bonifacio-OpenAir",
        date: "18/11/2023",
        description: "Explora las fotos de Bonifacio al Aire Libre y revive los buenos momentos.",
        image:  "/assets/bonifacio.jpg",
        url: "https://drive.google.com/drive/folders/16r4_mC-nAEOEUGEe22O76l7JD9hisX8q",
    },
    {
        id: 4,
        name: "Bonifacio",
        date: "12/12/2023",
        description: "Explora las fotos de Bonifacio y revive los buenos momentos.",
        image:  "/assets/bonifacio.jpg",
        url: "https://drive.google.com/drive/folders/16r4_mC-nAEOEUGEe22O76l7JD9hisX8q",
    },
    {
        id: 5,
        name: "Casbas",
        date: "10/1/2024",
        description: "Explora las fotos de Bonifacio y revive los buenos momentos.",
        image:  "/assets/bonifacio-OpenAir.jpg",
        url: "https://drive.google.com/drive/folders/16r4_mC-nAEOEUGEe22O76l7JD9hisX8q",
    },
    {
        id: 6,
        name: "Bonifacio-dePrueba",
        date: "18/11/2023",
        description: "Explora las fotos de Bonifacio al Aire Libre y revive los buenos momentos.",
        image:  "/assets/bonifacio.jpg",
        url: "https://drive.google.com/drive/folders/16r4_mC-nAEOEUGEe22O76l7JD9hisX8q",
    }
]
